export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FETCH_DATA_START = "FETCH_DATA_START";
export const SET_MIN_PE = "SET_MIN_PE";
