export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FETCH_DATA_STARTED = "FETCH_DATA_STARTED";
export const SET_MIN_PE = "SET_MIN_PE";
